# -*- coding: utf-8 -*-
"""SkillShift-Ai-Platform.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ILydr_n-awRbpmQba4J2t6TCzPCcVn37
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import joblib

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

sns.set(style="whitegrid")

from google.colab import drive
drive.mount('/content/drive')

caminho_csv = '/content/drive/MyDrive/Data_final.csv'  # ajuste se estiver em outra pasta
df = pd.read_csv(caminho_csv)

print("Formato do dataset:", df.shape)
df.head()

df.info()
print("\nEstatísticas descritivas:\n")
df.describe()

print("Quantidade de carreiras distintas:", df['Career'].nunique())
df['Career'].value_counts().head(15)

def map_career_area(career: str) -> str:
    c = str(career).lower()

    if any(k in c for k in ["engineer", "developer", "software", "data scientist", "scientist", "research", "it ", "systems", "network", "cyber", "ai ", "ml "]):
        return "Technology & Engineering"

    if any(k in c for k in ["doctor", "physician", "nurse", "surgeon", "dentist", "pharmacist", "therapist", "chiropractor", "psychologist", "psychiatrist", "health", "medical"]):
        return "Health & Life Sciences"

    if any(k in c for k in ["teacher", "professor", "educator", "instructor", "trainer", "school"]):
        return "Education"

    if any(k in c for k in ["accountant", "financial", "finance", "banker", "auditor", "analyst", "advisor", "planner", "economist", "investment", "business", "manager", "consultant", "marketing", "sales", "advertising", "hr ", "human resources", "recruiter"]):
        return "Business & Finance"

    if any(k in c for k in ["artist", "designer", "writer", "journalist", "actor", "musician", "film", "photographer", "stylist", "fashion", "director", "graphic"]):
        return "Creative & Media"

    if any(k in c for k in ["lawyer", "attorney", "judge", "magistrate", "prosecutor", "policy", "diplomat", "political", "foreign service"]):
        return "Law & Public Policy"

    if any(k in c for k in ["social worker", "social", "counselor", "counsellor", "human rights", "community"]):
        return "Social Services"

    if any(k in c for k in ["environmental", "climate", "ecologist"]):
        return "Environment & Sustainability"

    return "Other"

df['CareerArea'] = df['Career'].apply(map_career_area)
df[['Career', 'CareerArea']].head(10)

area_counts = df['CareerArea'].value_counts()
print(area_counts)

plt.figure(figsize=(8,5))
sns.barplot(y=area_counts.index, x=area_counts.values)
plt.title('Distribuição das áreas de carreira')
plt.xlabel('Quantidade de perfis')
plt.ylabel('Área de carreira')
plt.show()

contagens = df['CareerArea'].value_counts()
rare_areas = contagens[contagens < 8].index.tolist()

df['CareerAreaSimplified'] = df['CareerArea'].where(~df['CareerArea'].isin(rare_areas), "Other")

df['CareerAreaSimplified'].value_counts()

feature_cols = [
    'O_score', 'C_score', 'E_score', 'A_score', 'N_score',
    'Numerical Aptitude', 'Spatial Aptitude', 'Perceptual Aptitude',
    'Abstract Reasoning', 'Verbal Reasoning'
]

df['CareerArea3'] = df['CareerAreaSimplified'].replace({
    'Technology & Engineering': 'Tech',
    'Business & Finance': 'Business',
    'Creative & Media': 'Human',
    'Health & Life Sciences': 'Human',
    'Education': 'Human',
    'Social Services': 'Human',
    'Law & Public Policy': 'Human',
    'Other': 'Human'
})

df['CareerArea3'].value_counts()

area3_counts = df['CareerArea3'].value_counts()

plt.figure(figsize=(6,4))
sns.barplot(x=area3_counts.index, y=area3_counts.values)
plt.title('Distribuição das 3 macro-áreas de carreira')
plt.xlabel('Macro-área')
plt.ylabel('Quantidade de perfis')
plt.show()

area3_counts

X = df[feature_cols]
y = df['CareerArea3']

X.head(), y.head()

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

print("Tamanho treino:", X_train.shape)
print("Tamanho teste:", X_test.shape)
print("\nDistribuição no treino:\n", y_train.value_counts())
print("\nDistribuição no teste:\n", y_test.value_counts())

"""#####Observação:
##### Mantivemos o 'stratify=y' para garantir que as três macro-áreas apareçam
#####proporcionalmente no treino e no teste. Isso evita que o modelo fique tendencioso.
"""

modelo_3 = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    class_weight='balanced',
    min_samples_leaf=1,
    n_jobs=-1
)

modelo_3.fit(X_train, y_train)

"""##### Treinando o modelo com RandomForest ajustado para classes desbalanceadas.
#####Usamos class_weight='balanced' porque 'Human' domina o dataset.

"""

y_pred_3 = modelo_3.predict(X_test)

print("Acurácia (3 áreas):", accuracy_score(y_test, y_pred_3))
print("\nRelatório de classificação:\n")
print(classification_report(y_test, y_pred_3, zero_division=0))

# =========================
# Matriz de Confusão - 3 macro-áreas
# =========================

labels_3 = sorted(y.unique())

cm_3 = confusion_matrix(y_test, y_pred_3, labels=labels_3)

print("\nMatriz de Confusão (3 macro-áreas):")
print(cm_3)

plt.figure(figsize=(5,4))
sns.heatmap(
    cm_3,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=labels_3,
    yticklabels=labels_3
)
plt.title('Matriz de confusão - 3 macro-áreas')
plt.xlabel('Previsto')
plt.ylabel('Real')
plt.show()

"""### 🔍 Interpretação da matriz de confusão

- **Human** é a macro-área mais frequente no dataset e o modelo prevê bem (maior concentração na diagonal).
- **Business** e **Tech** têm amostras menores, mas ainda assim o modelo consegue captar alguns padrões.
- Erros acontecem principalmente na confusão entre *Human ↔ Business* e *Human ↔ Tech*, o que é esperado dada a sobreposição de perfis psicológicos.
- A acurácia de **62,5%** é sólida considerando somente 105 observações totais.

"""

# =====================================================
# MODELO 2 – AGRUPAMENTO DE PERFIS (K-MEANS CLUSTERING)
# =====================================================


X_cluster = df[feature_cols]

# 1) Padronização dos dados
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_cluster)

print("Shape dos dados escalados:", X_scaled.shape)

# 2) Treinando o modelo de clusterização (K-Means)
kmeans = KMeans(
    n_clusters=3,       # 3 grupos de perfis
    random_state=42,
    n_init=10
)

clusters = kmeans.fit_predict(X_scaled)

# 3) Guardamos o cluster de cada pessoa no DataFrame
df['Cluster'] = clusters

print("\nQuantidade de perfis em cada cluster:")
print(df['Cluster'].value_counts().sort_index())

# 4) Métrica de qualidade do agrupamento
sil_score = silhouette_score(X_scaled, clusters)
print(f"\nScore de silhueta (qualidade dos clusters): {sil_score:.3f}")

"""
- Usamos K-Means para criar 3 grupos de perfis com base nas notas de personalidade e aptidões.
- O 'silhouette_score' mede o quão bem os dados se separam em clusters (quanto mais próximo de 1, melhor).
- Esses clusters podem ser usados pelo SkillShift-AI para identificar "tipos de profissional"
  de forma não supervisionada (sem rótulo de carreira).
"""

# ============================================
# Analisando o perfil médio de cada cluster
# ============================================

cluster_profile = df.groupby('Cluster')[feature_cols].mean().round(2)
cluster_profile

# ============================================
# Visualizando a distribuição dos clusters
# ============================================

plt.figure(figsize=(6,4))
sns.countplot(x='Cluster', data=df)
plt.title('Distribuição dos clusters de perfil (K-Means)')
plt.xlabel('Cluster')
plt.ylabel('Quantidade de perfis')
plt.show()

# ============================================
# Salvando o modelo de clusters + scaler
# ============================================

objeto_clusters = {
    'scaler': scaler,
    'kmeans': kmeans,
    'feature_cols': feature_cols
}

caminho_clusters = '/content/modelo_perfis_clusters.joblib'
joblib.dump(objeto_clusters, caminho_clusters)

print(f"Modelo de clusters salvo em {caminho_clusters}")

caminho_modelo = '/content/modelo_career_area_3classes.joblib'
joblib.dump(modelo_3, caminho_modelo)
print(f"Modelo salvo em {caminho_modelo}")

from google.colab import files
files.download('/content/modelo_perfis_clusters.joblib')
files.download('/content/modelo_career_area_3classes.joblib')